name: ci_tutor_k8s

on:
  push:
    branches: [ "main" ]
    paths:
      - "chalix-theme/**"  

jobs:
  refresh-tutor-k8s:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install module
        run: |
          cd chalix-theme
          pip install .
      - name: Enable plugin
        run: TUTOR_ROOT=/home/alimento/chalix tutor plugins enable chalix_theme
      - name: Render Tutor environment
        run: TUTOR_ROOT=/home/alimento/chalix tutor config save
      - name: Build Tutor images
        run: TUTOR_ROOT=/home/alimento/chalix tutor images build openedx
      # - name: Push Tutor images
      #   run: TUTOR_ROOT=/home/alimento/chalix tutor images push openedx
      - name: Apply changes
        run: TUTOR_ROOT=/home/alimento/chalix tutor k8s upgrade
